In [2]:
import pandas as pd
pd.set_option('display.max_columns',False)
import numpy as np
import datetime as dt
import psycopg2
import seaborn as sns
import matplotlib.pyplot as plt
from wwo_hist import retrieve_hist_data
import os
import requests as re
from IPython.display import JSON

In [2]:
df_flights = pd.read_csv('cleaned_flights_2019sample1.csv')

In [3]:
df_flights = df_flights.sort_values(by=['fl_date'])

In [4]:
df_flights.head()

          fl_date op_unique_carrier origin  ... precipMM  visibility  windspeedKmph
13179  2019-01-01                QX    PHX  ...      0.1          10              8
6947   2019-01-01                OO    MSP  ...      0.2           9             13
12864  2019-01-01                UA    SLC  ...      0.0          10              7
7091   2019-01-01                WN    PHX  ...      0.1          10              8
15493  2019-01-01                WN    FLL  ...      1.4          10             12

[5 rows x 19 columns]

In [5]:
origin_cities = df_flights['origin'].unique()
origin_cities = list(origin_cities)

In [6]:
dest_cities = df_flights['dest'].unique()
dest_cities = list(dest_cities)

In [7]:
location_list = set(origin_cities).union(set(dest_cities))
location_list = list(location_list)

In [3]:
df_test = pd.read_csv('test_sample_cleaned.csv')

In [5]:
df_test.head()

      fl_date op_unique_carrier origin  ... weekday  crs_dep_bin  crs_arr_bin
0  2020-01-01                WN    ONT  ...       2        Night        Night
1  2020-01-01                WN    ONT  ...       2    Afternoon      Evening
2  2020-01-01                WN    ONT  ...       2        Night        Night
3  2020-01-01                WN    ONT  ...       2      Evening      Evening
4  2020-01-01                WN    ONT  ...       2    Afternoon    Afternoon

[5 rows x 12 columns]

In [8]:
origin_cities = df_test['origin'].unique()
origin_cities = list(origin_cities)

In [9]:
dest_cities = df_test['dest'].unique()
dest_cities = list(dest_cities)

In [21]:
location_list = set(origin_cities).union(set(dest_cities))
location_list = list(location_list)

In [27]:
location_list[95]

'SCE'

In [34]:
del location_list[:1]

In [ ]:
# missing XWA location

In [46]:
location_list = ['48.2582,103.7418']

In [13]:
len(list(location_list))

363

In [14]:
wwo_key = os.environ['wwo_key']

In [44]:
frequency = 24
start_date = '01-JAN-2020'
end_date = '07-JAN-2020'
api_key = wwo_key
location_list = location_list

In [47]:
hist_weather_data = retrieve_hist_data(api_key,
                                location_list,
                                start_date,
                                end_date,
                                frequency,
                                location_label = False,
                                export_csv = True,
                                store_df = True)

Retrieving weather data for 48.2582,103.7418


Currently retrieving data for 48.2582,103.7418: from 2020-01-01 to 2020-01-07
Time elapsed (hh:mm:ss.ms) 0:00:00.599470


export 48.2582,103.7418 completed!

Merging all the files together

In [31]:
path=r'C:\Users\Patrick\mid-term-project-I\WeatherData'

In [32]:
import glob
os.chdir(path)

In [29]:
len(all_filenames)

373

In [33]:
#create a list with all the filenames
extension = 'csv'
all_filenames = [i for i in glob.glob('*.{}'.format(extension))]

In [36]:
#combine all files in the list
combined_csv = pd.concat([pd.read_csv(f) for f in all_filenames ])
#export to csv
combined_csv.to_csv("weather.csv", index=False, encoding='utf-8-sig')

In [37]:
weather = pd.read_csv('weather.csv')

In [ ]:
weather

Merge 2020 csv files

In [50]:
path=r'C:\Users\Patrick\mid-term-project-I\WeatherData'

In [51]:
import glob
os.chdir(path)

In [52]:
#create a list with all the filenames
extension = 'csv'
all_filenames = [i for i in glob.glob('*.{}'.format(extension))]

In [53]:
len(all_filenames)

363

In [54]:
#combine all files in the list
combined_csv = pd.concat([pd.read_csv(f) for f in all_filenames ])
#export to csv
combined_csv.to_csv("jan2020_weather.csv", index=False, encoding='utf-8-sig')

In [55]:
jan_weather = pd.read_csv('jan2020_weather.csv')

In [56]:
jan_weather

       date_time  maxtempC  mintempC  ...  winddirDegree  windspeedKmph  location
0     2020-01-01         3        -2  ...            268             18       ABE
1     2020-01-02         7        -2  ...            238             12       ABE
2     2020-01-03         8        -1  ...            223              7       ABE
3     2020-01-04        11         1  ...            222              8       ABE
4     2020-01-05         4        -1  ...            295             18       ABE
...          ...       ...       ...  ...            ...            ...       ...
2536  2020-01-03        19        11  ...            104              9       YUM
2537  2020-01-04        21        11  ...             32              6       YUM
2538  2020-01-05        22        11  ...            226              8       YUM
2539  2020-01-06        20        11  ...            211             20       YUM
2540  2020-01-07        20        10  ...            306             13       YUM

[2541 rows x 25 columns]